### PR TITLE
 Have the user's username next to the userID in the query #95 

### LINKED ISSUE #95: Have the user's username next to the userID in the query
**Is your feature request related to a problem? Please describe.**
Running the query command outputs a text file that only has the userID. Makes it hard to differentiate which users are which. Treasurer requested for this. 

**Describe the solution you'd like**
Have the username next to the userID.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by c0untingNumbers**
Treasurer requested for an option of a csv file of usernames

closes #95 
https://github.com/ritsec/ops-bot-iii/issues/95

### CODE REVIEW

**Comment by 1nv8rzim** [comment]
Names used to be part of this, but Discord does ratelimiting with exponential backoff for resolving usernames via the api meaning that this query will take forever, for anything larger than like 10/20 people iirc

**Comment by c0untingNumbers** [comment]
This option is mostly going to be used by Treasurer. He's not going to use it too often.

I talked to the Treasurer about the query taking forever. He said he just needs it for receipts for competitions and meetings and I guess he doesn't mind waiting for it?

**Review by voxelvortex — APPROVED** [review]
LGTM

**Comment by 1nv8rzim** [comment]
I might have not been clear before when I said `query will take forever`, I didn't mean like a couple minutes, I mean like long enough that discord will not be able to access the interaction anymore and just not be able to send the results.

**Comment by c0untingNumbers** [comment]
Okay, not updating the main OBIII until I add some what of a delay for each call

**Pull request merged**
